export const moduleData = {
  customers: {
    title: 'Customer',
    listPath: '/dashboard/customers',
    nameField: 'name',
    records: [],
    fields: [
      { name: 'name', label: 'Full Name', type: 'text' },
      { name: 'email', label: 'Email Address', type: 'email' },
      { name: 'phone', label: 'Contact Number', type: 'tel' },
      { name: 'address', label: 'Street Address', type: 'text' },
      { name: 'status', label: 'Account Status', type: 'select', options: ['Active', 'Inactive'] },
    ],
  },
  vehicles: {
    title: 'Vehicle',
    listPath: '/dashboard/vehicles',
    nameField: 'name',
    records: [],
    fields: [
      { name: 'name', label: 'Vehicle Name', type: 'text' },
      { name: 'plate', label: 'Plate Number', type: 'text' },
      { name: 'modelRef', label: 'Model Reference', type: 'text' },
      { name: 'year', label: 'Year of Manufacture', type: 'text' },
      { name: 'engineRef', label: 'Engine Reference', type: 'text' },
      { name: 'chassisRef', label: 'Chassis Reference', type: 'text' },
      { name: 'status', label: 'Operational Status', type: 'select', options: ['Available', 'In Use', 'Maintenance'] },

      // Compliance Section
      { name: 'insuranceExpiry', label: 'Insurance Expiry Date', type: 'date', section: 'Compliance & Legal' },
      { name: 'registrationExpiry', label: 'Registration Expiry Date', type: 'date', section: 'Compliance & Legal' },
    ],
  },
  expenses: {
    title: 'Expense',
    listPath: '/dashboard/expenses',
    nameField: 'id',
    records: [],
    fields: [
      { name: 'date', label: 'Transaction Date', type: 'date' },
      { name: 'amount', label: 'Expense Amount (QAR)', type: 'number' },
      { name: 'description', label: 'Expense Description', type: 'text' },
      { name: 'worker', label: 'Assigned Worker', type: 'select', module: 'users' },
      { name: 'workerId', label: 'Worker Mongo ID', type: 'text', hidden: true, required: false },
      { name: 'vehicle', label: 'Associated Vehicle', type: 'select', module: 'vehicles' },
      { name: 'vehicleId', label: 'Vehicle Mongo ID', type: 'text', hidden: true, required: false },
    ],
  },
  invoices: {
    title: 'Invoice',
    listPath: '/dashboard/invoices',
    nameField: 'id',
    records: [],
    fields: [
      { name: 'jobId', label: 'Job ID', type: 'select', module: 'tows', required: true },
      { name: 'towId', label: 'Tow Mongo ID', type: 'text', hidden: true, required: false },
      { name: 'customer', label: 'Customer Name', type: 'text', readOnly: true },
      { name: 'customerId', label: 'Customer Mongo ID', type: 'text', hidden: true, required: false },
      { name: 'worker', label: 'Assigned Worker', type: 'text', readOnly: true },
      { name: 'workerId', label: 'Worker Mongo ID', type: 'text', hidden: true, required: false },
      { name: 'vehicle', label: 'Vehicle Used', type: 'text', readOnly: true },
      { name: 'vehicleId', label: 'Vehicle Mongo ID', type: 'text', hidden: true, required: false },
      { name: 'date', label: 'Billing Date', type: 'date' },
      { name: 'type', label: 'Payment Type', type: 'select', options: ['Cash', 'Card', 'Bank Transfer', 'Credit'], defaultValue: 'Credit' },
      { name: 'total', label: 'Total Billed Amount (QAR)', type: 'number', defaultValue: 0 },
      { name: 'paid', label: 'Total Paid Amount (QAR)', type: 'number', defaultValue: 0 },
      { name: 'status', label: 'Payment Status', type: 'text', readOnly: true, defaultValue: 'Unpaid' },
    ],
  },
  quotations: {
    title: 'Quotation',
    listPath: '/dashboard/quotations',
    nameField: 'id',
    records: [],
    fields: [
      { name: 'customer', label: 'Customer Name', type: 'select', module: 'customers' },
      { name: 'customerId', label: 'Customer Mongo ID', type: 'text', hidden: true, required: false },
      { name: 'driver', label: 'Assigned Driver', type: 'select', module: 'users' },
      { name: 'driverId', label: 'Worker Mongo ID', type: 'text', hidden: true, required: false },
      { name: 'vehicle', label: 'Vehicle', type: 'select', module: 'vehicles' },
      { name: 'vehicleId', label: 'Vehicle Mongo ID', type: 'text', hidden: true, required: false },
      { name: 'pickup', label: 'Pickup Location', type: 'text' },
      { name: 'dropoff', label: 'Drop-off Location', type: 'text' },
      { name: 'date', label: 'Estimated Date', type: 'date' },
      { name: 'amount', label: 'Quoted Amount (QAR)', type: 'number' },
      { name: 'status', label: 'Quote Status', type: 'select', options: ['Draft', 'Sent', 'Approved', 'Rejected'], hidden: true, defaultValue: 'Draft' },
    ],
  },
  tows: {
    title: 'Tow Job',
    listPath: '/dashboard/tows',
    nameField: 'id',
    records: [],
    fields: [
      { name: 'customer', label: 'Customer Name', type: 'select', module: 'customers', allowQuickAdd: true },
      { name: 'customerId', label: 'Customer Mongo ID', type: 'text', hidden: true, required: false },
      { name: 'vehicle', label: 'Vehicle', type: 'select', module: 'vehicles' },
      { name: 'vehicleId', label: 'Vehicle Mongo ID', type: 'text', hidden: true, required: false },
      { name: 'driver', label: 'Worker', type: 'select', module: 'users' },
      { name: 'driverId', label: 'Worker Mongo ID', type: 'text', hidden: true, required: false },
      { name: 'pickup', label: 'Pickup Location / Address', type: 'text' },
      { name: 'pickupPhoto', label: 'Pickup Photo (Proof of Condition)', type: 'file' },
      { name: 'dropoff', label: 'Drop-off Location / Address', type: 'text' },
      { name: 'dropoffPhoto', label: 'Drop-off Photo (Proof of Condition)', type: 'file' },
      { name: 'date', label: 'Service Date', type: 'date' },
      { name: 'paymentMethod', label: 'Payment Method', type: 'select', options: ['Cash', 'Card', 'Bank Transfer'] },
      { name: 'amount', label: 'Service Charges (QAR)', type: 'number' },
      { name: 'driverShare', label: 'Driver Share (10%)', type: 'number', readOnly: true, section: 'Internal Split' },
      { name: 'companyShare', label: 'Company Share (90%)', type: 'number', readOnly: true, section: 'Internal Split' },
      { name: 'status', label: 'Job Status', type: 'select', options: ['Pending', 'In Progress', 'Completed', 'Cancelled'] },
    ],
  },

  salaries: {
    title: 'Salary Payment',
    listPath: '/dashboard/salaries',
    nameField: 'id',
    records: [],
    fields: [
      { name: 'month', label: 'Payroll Month', type: 'select', options: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] },
      { name: 'year', label: 'Payroll Year', type: 'select', options: ['2024', '2025', '2026', '2027', '2028', '2029', '2030', '2031', '2032', '2033', '2034', '2035'] },
      { name: 'worker', label: 'Employee Name', type: 'select', module: 'users' },
      { name: 'workerId', label: 'Worker Mongo ID', type: 'text', hidden: true, required: false },
      { name: 'baseSalary', label: 'Monthly Base Salary (QAR)', type: 'number', readOnly: true, defaultValue: 0 },
      { name: 'cashCollected', label: 'Total Cash Collected (QAR)', type: 'number', readOnly: true, defaultValue: 0 },
      { name: 'retention', label: 'Driver Commission (10%)', type: 'number', readOnly: true, defaultValue: 0 },
      { name: 'cashDeduction90', label: 'Cash Deduction (90%)', type: 'number', readOnly: true, defaultValue: 0 },
      { name: 'expenses', label: 'Expense Deductions (QAR)', type: 'number', readOnly: true, defaultValue: 0 },
      { name: 'amount', label: 'Net Payable Amount (QAR)', type: 'number', readOnly: true, defaultValue: 0 },
      { name: 'status', label: 'Payment Status', type: 'select', options: ['Paid', 'Pending'] },
    ],
  },

  notifications: {
    title: 'Notification',
    listPath: '/dashboard/notifications',
    nameField: 'title',
    records: [],
    fields: [
      { name: 'title', label: 'Notification Title', type: 'text' },
      { name: 'message', label: 'Notification Message', type: 'text' },
      { name: 'time', label: 'Time Received', type: 'text' },
      { name: 'type', label: 'Category', type: 'select', options: ['tow', 'payment', 'alert', 'status'] },
      { name: 'unread', label: 'Is Unread?', type: 'select', options: ['true', 'false'] },
    ],
  },
  users: {
    title: 'User Management',
    listPath: '/dashboard/users',
    nameField: 'name',
    records: [
      { id: 'USR-001', name: 'System Admin', password: 'admin123', email: 'admin@falcon.com', role: 'Administrator' }
    ],
    fields: [
      { name: 'id', label: 'Employee ID', type: 'text' },
      { name: 'name', label: 'Full Name', type: 'text' },
      { name: 'password', label: 'Password', type: 'password' },
      { name: 'email', label: 'Email Address', type: 'email' },
      { name: 'phone', label: 'Mobile Number', type: 'tel' },
      { name: 'role', label: 'User Role', type: 'select', options: ['Administrator', 'Worker'] },
      { name: 'salary', label: 'Monthly Base Salary (QAR)', type: 'number', defaultValue: 0 },
      { name: 'status', label: 'Employment Status', type: 'select', options: ['Active', 'On Leave', 'Inactive'] },
    ],
  },
};

export function getModuleRecord(moduleKey, id) {
  const config = moduleData[moduleKey];
  return config?.records.find((record) => record.id === id) ?? config?.records[0];
}
